### ISSUE TITLE
🔖 Changelog update

### ISSUE THREAD

**Issue by llGanhzll** [TheTiket/issues#49]
## Description
Realizar un Changelog de lo que se va a subir a produccion en la version 4.4.0

## TODO

WEB
- [ ] Dashboard general para GIS
- [ ] Add option to include Calendar in Dashboard
- [ ] Dashboard Vista Cliente
- [ ] Gráfico de ahorro
- [ ] Corregir envios de cotización por correo
- [ ] Corregir reporte final PDF
- [ ] Crear una inspección indivualizada por servicio

APP
- [x] ⚡️ Improve app's performance
- [x]  🔨 Calculate drained Weight
- [x] :ambulance: Verify reefer container
- [x]  🐛 Fix the accept colors of the elements
- [x]  🐛 Fix data loss after optimization
- [x] 🔨 Show tasks according to their criticality and sample size
- [x] 🔨 Update lot identification in app
- [x] ACTULIZAR VERSION DE LA APP A LA VERSION 4.4.0
- [ ] Agregar reinspección una vez que este hecho 

-[ ] Utilizar github
