### ISSUE TITLE
🚀  Upload to play store

### ISSUE THREAD

**Issue by llGanhzll** [TheTiket/issues#50]
# TODO

- [x] Crear nueva cuenta de administrador en Google console
- [x] Cambiar keystore
- [x] Actualizar carpeta de android con nueva empresa "com.thetiket.thetiket"
- [x] Realizar verificación de ID (Enrique)
- [x] Terminar panel de configuracion de la app
- [ ] Documentar proceso de subida de la app a la playstore y la creación de una apk
- [x] Realizar prueba interna
- [x] Realizar prueba cerrada
- [x] Lanzar app a producción 
- [x] Subir app a web dev
- [x] Subir app a web prod
- [x] Crear APK dev
- [x] Crear APK prod
- [x] Crear .abb prod
- [x] Agregar alertas para ver funciones para solicitar permisos 
- [ ]  Agregar Privacy Policy nueva en la app y en la web
