### ISSUE TITLE
🚀 Update Webside to enviroment prod

### ISSUE THREAD

**Issue by llGanhzll** [TheTiket/issues#52]
# Description
Subir ultimos cambio de la rama development a la base de datos en produccion.

## TODO

- [x] Ocultar socios de IT a coordinadores de GIS
- [x] Ocultar calendario de la opcion operaciones del board
- [x] Ocultar del form de creacion de tiket categorias
- [x] Sacar boton flotante de transporte en home app
- [x] Sacar filtros de Ciudad, Categoría y sub categoría

**Comment by llGanhzll** [comment]
Cuando subamos el ambiente de produccion ojo con eso, los coordinadores de GIS pueden ver los socios de IT

![image](https://user-images.githubusercontent.com/102160740/171423527-ebba9c6c-3361-4f68-9a18-207b584438fd.png)

**Comment by llGanhzll** [comment]
No se si se daño este modulo del programa pero creo que no va a ir a prod

![image](https://user-images.githubusercontent.com/102160740/171424073-e27774a9-8053-477e-bfeb-142d00346a7e.png)

**Comment by llGanhzll** [comment]
Sacar categorias si no la vamos a usar en GIS

![image](https://user-images.githubusercontent.com/102160740/171424588-a6059b2e-90a3-45f3-8d68-3b6926533b5c.png)

**Comment by llGanhzll** [comment]
No tiene ninguna utilidad sacar

![image](https://user-images.githubusercontent.com/102160740/171426221-f4ff5659-0708-4274-9fc7-b12b27b0b2c2.png)

**Comment by llGanhzll** [comment]
Sacar estos filtros

![Image](https://user-images.githubusercontent.com/102160740/171428773-5da42f72-d83f-459c-a2a8-dd939536f39d.png)
