### ISSUE TITLE
♻️ Cambiar lógica de la descarga de datos para el funcionamiento de la orden de trabajo v3

### ISSUE THREAD

**Issue by hectorveas** [TheTiket/issues#77]
Cuando se tengan otros tiket cada vez que se acepte el tiket y antes de que se descargue el WOD se debe inicializar con las entidades(task, shapes, controles) guardadas en una nueva coleccion que tiene una referencia del tiketId

## TO-DO

- [x] [BD] Crear el modelo( agregar coleccion tiketsData)
- [x] [web] Al crear el tiket, guardar la copia
- [x] [App] Quitar la obtencion de datos para traer entidades (Tareas, Shapes, Controles)
- [x] [App] Traer copia de los datos del tiket
- [x] [App] Cambiar todas las referencias por la copia traida
- [x] [Web] Cambiar todas las referencias por la copia traida (al generar el reporte(pdf y excel))

### Iteraciones de optimizacion de descarga de datos en app

![Image](https://user-images.githubusercontent.com/32781681/180829597-8b7bb38a-2ff2-4746-a7f2-91e196e11507.png)

### Detalles reunión

![Image](https://user-images.githubusercontent.com/32781681/180830296-eae61e06-971d-4e8d-b7be-1d31d1d1c3f7.png)
