### ISSUE TITLE
♻️ Cambiar lógica de la descarga de datos para el funcionamiento de la orden de trabajo v4

### ISSUE THREAD

**Issue by hectorveas** [TheTiket/issues#99]
Cuando se tengan otros tiket cada vez que se acepte el tiket y antes de que se descargue el WOD se debe inicializar con las entidades(categories y items) guardadas en una nueva colección que tiene una referencia del tiketId

## TO-DO

- [x] [BD] agregar al modelo categories y items
- [x] [App] Quitar la obtención de datos para traer entidades (categories y items)
- [x] [App] Traer copia de los datos del tiket
- [x] [App] Cambiar todas las referencias por la copia traida
- [x] [Web] Cambiar todas las referencias por la copia traida (al generar el reporte(pdf y excel))
